export const questions = {
  success: true,
  message: 'success',
  data: [
    {
      id: 11,
      user: {
        id: 12,
        firstname: 'Muhammad',
        lastname: 'Hamdy',
        username: 'modclover7@gmail.com',
        email: 'modclover7@gmail.com',
        profilePicture: null,
      },
      title: 'Post Tilte 1',
      content: 'Content String',
      votes: [],
      createdAt: '2023-09-18T09:51:34.626+00:00',
    },
    {
      id: 12,
      user: {
        id: 12,
        firstname: 'Muhammad',
        lastname: 'Hamdy',
        username: 'modclover7@gmail.com',
        email: 'modclover7@gmail.com',
        profilePicture: null,
      },
      title: 'Post Tilte 2',
      content: 'Content String',
      votes: [],
      createdAt: '2023-09-18T09:51:37.343+00:00',
    },
    {
      id: 13,
      user: {
        id: 12,
        firstname: 'Muhammad',
        lastname: 'Hamdy',
        username: 'modclover7@gmail.com',
        email: 'modclover7@gmail.com',
        profilePicture: null,
      },
      title: 'Post Tilte 3',
      content: 'Content String',
      votes: [],
      createdAt: '2023-09-18T09:51:39.190+00:00',
    },
    {
      id: 14,
      user: {
        id: 12,
        firstname: 'Muhammad',
        lastname: 'Hamdy',
        username: 'modclover7@gmail.com',
        email: 'modclover7@gmail.com',
        profilePicture: null,
      },
      title: 'Post Tilte 4',
      content: 'Content String',
      votes: [],
      createdAt: '2023-09-18T09:51:40.636+00:00',
    },
    {
      id: 15,
      user: {
        id: 12,
        firstname: 'Muhammad',
        lastname: 'Hamdy',
        username: 'modclover7@gmail.com',
        email: 'modclover7@gmail.com',
        profilePicture: null,
      },
      title: 'Post Tilte 5',
      content: 'Content String',
      votes: [],
      createdAt: '2023-09-18T09:51:42.193+00:00',
    },
    {
      id: 16,
      user: {
        id: 12,
        firstname: 'Muhammad',
        lastname: 'Hamdy',
        username: 'modclover7@gmail.com',
        email: 'modclover7@gmail.com',
        profilePicture: null,
      },
      title: 'Post Tilte 6',
      content: 'Content String',
      votes: [],
      createdAt: '2023-09-18T09:51:44.417+00:00',
    },
    {
      id: 17,
      user: {
        id: 12,
        firstname: 'Muhammad',
        lastname: 'Hamdy',
        username: 'modclover7@gmail.com',
        email: 'modclover7@gmail.com',
        profilePicture: null,
      },
      title: 'Post Tilte 7',
      content: 'Content String',
      votes: [],
      createdAt: '2023-09-18T09:51:46.176+00:00',
    },
    {
      id: 18,
      user: {
        id: 12,
        firstname: 'Muhammad',
        lastname: 'Hamdy',
        username: 'modclover7@gmail.com',
        email: 'modclover7@gmail.com',
        profilePicture: null,
      },
      title: 'Post Tilte 8',
      content: 'Content String',
      votes: [],
      createdAt: '2023-09-18T09:51:47.827+00:00',
    },
    {
      id: 19,
      user: {
        id: 12,
        firstname: 'Muhammad',
        lastname: 'Hamdy',
        username: 'modclover7@gmail.com',
        email: 'modclover7@gmail.com',
        profilePicture: null,
      },
      title: 'Post Tilte 9',
      content: 'Content String',
      votes: [],
      createdAt: '2023-09-18T09:51:49.637+00:00',
    },
    {
      id: 20,
      user: {
        id: 12,
        firstname: 'Muhammad',
        lastname: 'Hamdy',
        username: 'modclover7@gmail.com',
        email: 'modclover7@gmail.com',
        profilePicture: null,
      },
      title: 'Post Tilte 10',
      content: 'Content String',
      votes: [],
      createdAt: '2023-09-18T09:51:52.286+00:00',
    },
  ],
};
