spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/DevAskDB
    username: postgres
    password:
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

application:
  security:
    jwt: # for development
      token:
        secret-key: "3fae524f16942d00e2cea83e89c7e13d57f7598b66e9341fcf312eeaa8479baa"
        expiration-in-seconds: 86400000
        issuer: ""
        audience: ""
        refresh-token:
          expiration-in-seconds: 604800000